import type { EditorialBoardMember } from "./types"

export const editorialBoardMembers: EditorialBoardMember[] = [
  {
    id: "1",
    name: "Prof. Eleanor Blackwood",
    designation: "Editor-in-Chief",
    image: "/placeholder.svg?height=400&width=400",
    order: 1,
    bio: "Professor of Constitutional Law at Yale Law School with over 25 years of experience in legal scholarship.",
    email: "eblackwood@legalinsight.com",
  },
  {
    id: "2",
    name: "Dr. Marcus Reynolds",
    designation: "Managing Editor",
    image: "/placeholder.svg?height=400&width=400",
    order: 2,
    bio: "Former clerk to Supreme Court Justice and specialist in judicial politics and constitutional interpretation.",
    email: "mreynolds@legalinsight.com",
  },
  {
    id: "3",
    name: "Prof. Sophia Chen",
    designation: "Senior Editor, Constitutional Law",
    image: "/placeholder.svg?height=400&width=400",
    order: 3,
    bio: "Award-winning scholar focusing on comparative constitutional law and democratic theory.",
    email: "schen@legalinsight.com",
  },
  {
    id: "4",
    name: "Judge Robert Harrington",
    designation: "Senior Editor, Judicial Affairs",
    image: "/placeholder.svg?height=400&width=400",
    order: 4,
    bio: "Retired federal judge with extensive experience in complex constitutional litigation.",
    email: "rharrington@legalinsight.com",
  },
  {
    id: "5",
    name: "Dr. Amara Washington",
    designation: "Senior Editor, Legal History",
    image: "/placeholder.svg?height=400&width=400",
    order: 5,
    bio: "Legal historian specializing in the development of constitutional doctrine in the 20th century.",
    email: "awashington@legalinsight.com",
  },
  {
    id: "6",
    name: "Prof. James Okafor",
    designation: "Senior Editor, International Law",
    image: "/placeholder.svg?height=400&width=400",
    order: 6,
    bio: "Expert in international human rights law and its intersection with domestic constitutional protections.",
    email: "jokafor@legalinsight.com",
  },
  {
    id: "7",
    name: "Dr. Leila Patel",
    designation: "Associate Editor",
    image: "/placeholder.svg?height=400&width=400",
    order: 7,
    bio: "Specialist in administrative law and regulatory policy with a focus on environmental regulations.",
    email: "lpatel@legalinsight.com",
  },
  {
    id: "8",
    name: "Prof. Thomas Grayson",
    designation: "Associate Editor",
    image: "/placeholder.svg?height=400&width=400",
    order: 8,
    bio: "Scholar of federalism and state constitutional law with particular interest in local government authority.",
    email: "tgrayson@legalinsight.com",
  },
]
